networks:
  tibia:
    driver: bridge

services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:22.04
    networks:
      - tibia
    command:
      - /bin/sh
      - -c
      - |
        if ! command -v wget > /dev/null 2>&1; then
          apt update 
          apt install -y wget imagemagick xvfb libbrotli1 libegl1 libgl1-mesa-glx libgles2 libx11-6 libfontconfig1 libxkbcommon0 libdbus-1-3 libopengl0 libxcb-xinerama0 libxcb-cursor0 libxcb-xinerama0
          apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        fi

        if [ ! -f tibia.x64.tar.gz ]; then
          wget https://static.tibia.com/download/tibia.x64.tar.gz
        fi

        if [ ! -d Tibia ]; then
          tar -xzvf tibia.x64.tar.gz
        fi

        Xvfb :1 -screen 5 1024x768x8 &
        DISPLAY=:1 /Tibia/Tibia
        DISPLAY=:1 /Tibia/Tibia &
        sleep 5
        import -display :1 -window root screenshot.png
        tail -f /dev/null
